### ISSUE TITLE
물품 거래 기능 구현

### ISSUE THREAD

**Issue by cocahack** [f-lab-edu/fream#3]
## 구현할 기능 목록

- [ ] 물품 판매/구매
    - [ ] 판매 / 구매 입찰 등록
    - [ ] 물품 구매
    - [ ] 내가 등록한 입찰 내역 조회

**Comment by f-lab-joseph** [comment]
이슈가 너무 큰 단위로 등록되어있는 것 같습니다. 
좀 더 작은 단위로 나눠주시면 좋을 것 같습니다. 
 
하나의 이슈를 통해 기능을 구현하면 PR 이 너무나 커집니다.

**Comment by cocahack** [comment]
큰 단위의 이슈와 그 이슈에서 파생되는 작은 이슈를 더 만들어서 계층적인 구조로 이슈를 관리할 생각이었습니다.

그런데 좀 생각해보니 이렇게 하는것 보다는 깃헙 마일스톤 기능을 쓰는게 더 낫겠다는 생각이 문득 들었습니다. 

#1, #2, #3 세 이슈는 close 하고 마일스톤으로 만들어서 이슈 관리해보겠습니다.

**Comment by cocahack** [comment]
https://github.com/f-lab-edu/fream/milestone/1

큰 단위의 이슈 대신 마일스톤으로 세부 이슈 및 일정 확인
