### ISSUE TITLE
상품 검색 기능

### ISSUE THREAD

**Issue by cocahack** [f-lab-edu/fream#7]
### 요구 조건

- 입력된 키워드를 브랜드 및 상품 이름과 비교한다.
- 브랜드와 상품 이름 각각의 유사도를 먼저 확인하고, 둘의 정렬 기준을 마련해야한다. 
- 키워드는 한국어 또는 영어이다

#### Option

- 줄임말, 별명 등으로 검색
    - 예시
        - Supreme x The North Face 콜라보 제품: 슈노
        - Offwhite: 옾화

**Comment by cocahack** [comment]
@HyundeokPark 기능 구현 전에 요구 사항 정리해봤습니다. 의견 있으시면 주세요.

@f-lab-joseph 줄임말, 별명으로 검색이 가능하려면 어떻게 해야할까요? 프로젝트의 범위를 벗어나는 기능인지 파악이 어렵네요..

**Comment by f-lab-joseph** [comment]
줄임말, 별명 검색은 프로젝트 범위를 벗어날 것 같습니다. 1차에서는 검색은 심플하게 구현해주세요ㅎ
